spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/phoneshopmvc
   username: phoneshopmvc
   password: admin
  jpa:
   properties:
    hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
    ddl-auto: update
  mvc:
   pathmatch:
    matching-strategy: ant_path_matcher	 
#spring:
#  datasource:
#   url: jdbc:h2:mem:testdb
#   username: sa
#   password: 
#  jpa:
#   properties:
#    hibernate:
#    dialect: org.hibernate.dialect.H2Dialect
#   hibernate:
#    ddl-auto: create
#  h2:
#    console:
#      enabled: true